name: "Set issue state"

on:
  project_card:
    types: [created, edited, moved]

jobs:
  set-state:
    runs-on: ubuntu-22.04
    steps:
      - uses: dessant/issue-states@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
